security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_database:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_database
            entry_point: form_login
            custom_authenticator: App\Security\LoginAuthenticator
            form_login:
                login_path: connexion
                check_path: connexion
            logout:
                path: deconnexion
                target: connexion

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/employe, roles: ROLE_EMPLOYE }
        - { path: ^/conducteur, roles: ROLE_CONDUCTEUR }
        - { path: ^/passager, roles: ROLE_PASSAGER }
