security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: [ROLE_EMPLOYE, ROLE_USER]
        ROLE_EMPLOYE: [ROLE_USER]
        
    providers:
        users_in_database:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_database
            custom_authenticator: App\Security\LoginAuthenticator
            entry_point: App\Security\LoginAuthenticator
            logout:
                path: deconnexion
                target: connexion

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/employe, roles: ROLE_EMPLOYE }
        - { path: ^/conducteur, roles: ROLE_USER }
        - { path: ^/passager, roles: ROLE_USER }
